# Generated by Django 2.2.3 on 2019-08-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('time_total', models.TimeField()),
                ('walk_time', models.TimeField()),
                ('run_time', models.TimeField()),
                ('hike_time', models.TimeField()),
                ('bike_time', models.TimeField()),
                ('swim_time', models.TimeField()),
            ],
        ),
    ]
