# Generated by Django 2.2.3 on 2019-08-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_auto_20190804_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totals',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
