# Generated by Django 2.2.3 on 2019-08-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0004_auto_20190804_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='totals',
            name='bike_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='totals',
            name='distance_km',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='totals',
            name='hike_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='totals',
            name='run_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='totals',
            name='swim_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='totals',
            name='time_total',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='totals',
            name='walk_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
