# Generated by Django 2.2.3 on 2019-08-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0005_auto_20190805_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time_stamp',
            field=models.TimeField(),
        ),
    ]
