# Generated by Django 2.2.3 on 2019-08-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0006_auto_20190805_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totals',
            name='bike_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totals',
            name='hike_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totals',
            name='other_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totals',
            name='run_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totals',
            name='swim_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totals',
            name='time_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totals',
            name='walk_time',
            field=models.IntegerField(),
        ),
    ]
